export const READ_EMAIL = 'READ_EMAIL';
export const SET_AS_SPAM = 'SET_AS_SPAM';
export const SET_AS_UNREAD = 'SET_AS_UNREAD';
export const SET_AS_DELETED = 'SET_AS_DELETED';
export const EMAILS_RECIEVE = 'EMAILS_RECIEVE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';